[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arxiv>=2.1.3",
    "mistralai>=1.5.1",
    "requests>=2.32.3",
    "tqdm>=4.67.1",
]
