name: Release to PyPI

on:
    push:
        branches:
            - main

jobs:
    release:
        name: Build and Publish
        runs-on: ubuntu-latest
        permissions:
            # Required for trusted publishing to PyPI
            id-token: write
            contents: write # Needed for creating tags

        steps:
            - name: Check out repository
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install build twine setuptools wheel

            - name: Extract current version
              id: extract_version
              run: |
                  VERSION=$(python -c "from papertuner import __version__; print(__version__)")
                  echo "VERSION=$VERSION" >> $GITHUB_ENV
                  echo "Current version: $VERSION"

            - name: Create Git tag if it doesn't exist
              run: |
                  if ! git rev-parse "v$VERSION" >/dev/null 2>&1; then
                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"
                    git tag -a "v$VERSION" -m "Release v$VERSION"
                    git push origin "v$VERSION"
                    echo "Created and pushed tag v$VERSION"
                  else
                    echo "Tag v$VERSION already exists, skipping tag creation"
                  fi

            - name: Build package
              run: python -m build

            - name: Check distribution
              run: twine check dist/*

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
